### ISSUE TITLE
Just found this mod. Works great. Thanks for making it.

### ISSUE THREAD

**Issue by 0megq** [HotLava03/rich-presence-mod#1]
Thank you for making this mod. I really needed and it came in clutch. Keep at it.

**Comment by tierrif** [comment]
Hey,

Thanks for your feedback. I'm happy you enjoyed the mod, and most importantly found it useful. Unfortunately I lack time at this very moment, so I can't work on this mod at the time I write this. It is quite unstable, even though it may "minimally" work. Player count breaks easily, the settings aren't very user friendly, etc. When I have time again, I will attempt working on it again, but I don't promise anything. This is a small project I started after all.

Have a nice day!
